name: ROS nodes

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ros2_node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [humble, jazzy]
    container: osrf/ros:${{ matrix.release }}-desktop
    steps:
      - uses: actions/checkout@v4
      - name: Run colcon
        run: source /opt/ros/${{ matrix.release }}/setup.bash && colcon build --event-handlers console_direct+
        shell: bash
